### ISSUE TITLE
monterey freezes 

### ISSUE THREAD

**Issue by Harsh-1812** [dnsdk/Dell-Precision-5510-MacOS#2]
Monterey freezes after 10 - 20 minutes of use, but bigsur works perfectly  👍

**Comment by dnsdk** [comment]
> Monterey freezes after 10 - 20 minutes of use, but bigsur works perfectly 👍

The freezes problem is FakePCIID ，not resolved yet

**Comment by dnsdk** [comment]
> Monterey freezes after 10 - 20 minutes of use, but bigsur works perfectly 👍

freeze resolved

**Comment by Harsh-1812** [comment]
:)

**Comment by Harsh-1812** [comment]
After a day use, no more freeze issue.....but HDMI not working.
