### ISSUE TITLE
触控板无效？

### ISSUE THREAD

**Issue by betaLi-pixel** [dnsdk/Dell-Precision-5510-MacOS#4]
首先谢谢大神的EFI~~
偶尔在GitHub搜索5510然后看到你的EFI更新日期很新，下载安装12.0.1正式版竟然意外的顺利无任何问题，没换网卡，触控板有设置界面但是触摸和点击都无反应，不知道是不是bios设置还是啥问题呢~

**Comment by dnsdk** [comment]
> 



> 首先谢谢大神的EFI~~偶尔在GitHub搜索5510然后看到你的EFI更新日期很新，下载安装12.0.1正式版竟然意外的顺利无任何问题，没换网卡，触控板有设置界面但是触摸和点击都无反应，不知道是不是bios设置还是啥问题呢~

蛤 我的触控板是好的，多指手势也没问题。另外触屏也能用
